export const INSIGHTS_TOPIC_LOAD_CHART_START = "INSIGHTS_TOPIC_LOAD_CHART_START"
export const INSIGHTS_TOPIC_LOAD_CHART_SUCCESS = "INSIGHTS_TOPIC_LOAD_CHART_SUCCESS"
export const INSIGHTS_TOPIC_LOAD_CHART_FAILURE = "INSIGHTS_TOPIC_LOAD_CHART_FAILURE"

export const INSIGHTS_TOPIC_CHANGE_DROPDOWN = "INSIGHTS_TOPIC_CHANGE_DROPDOWN"
export const INSIGHTS_TOPIC_CLICK_BAR = "INSIGHTS_TOPIC_CLICK_BAR"
export const INSIGHTS_TOPIC_CLICK_VIEW_QUESTION = "INSIGHTS_TOPIC_CLICK_VIEW_QUESTION"
export const INSIGHTS_TOPIC_CLOSE_MODAL = "INSIGHTS_TOPIC_CLOSE_MODAL"
