export const QUIZ_LOAD_MODULE_QUIZZES = "QUIZ_LOAD_MODULE_QUIZZES"
export const QUIZ_LOAD_MODULE_QUIZZES_SUCCESS = "QUIZ_LOAD_MODULE_QUIZZES_SUCCESS"
export const QUIZ_LOAD_MODULE_QUIZZES_FAILURE = "QUIZ_LOAD_MODULE_QUIZZES_FAILURE"
