export const QUIZ_CREATION_CHANGE_TAB = 'QUIZ_CREATION_CHANGE_TAB'
export const QUIZ_CREATION_OPEN_PREVIEW = 'QUIZ_CREATION_OPEN_PREVIEW'
export const QUIZ_CREATION_CLOSE_PREVIEW = 'QUIZ_CREATION_CLOSE_PREVIEW'
