export const QUIZ_CREATION_CHANGE_TAB = 'QUIZ_CREATION_CHANGE_TAB'
export const QUIZ_CREATION_CHANGE_STEP = 'QUIZ_CREATION_CHANGE_STEP'
export const QUIZ_CREATION_OPEN_PREVIEW = 'QUIZ_CREATION_OPEN_PREVIEW'
export const QUIZ_CREATION_CLOSE_PREVIEW = 'QUIZ_CREATION_CLOSE_PREVIEW'

export const QUIZ_CREATION_CHANGE_TITLE = "QUIZ_CREATION_CHANGE_TITLE"
export const QUIZ_CREATION_CHANGE_OPENING_DATE = "QUIZ_CREATION_CHANGE_OPENING_DATE"
export const QUIZ_CREATION_CHANGE_OPENING_TIME = "QUIZ_CREATION_CHANGE_OPENING_TIME"
export const QUIZ_CREATION_CHANGE_CLOSING_DATE = "QUIZ_CREATION_CHANGE_CLOSING_DATE"
export const QUIZ_CREATION_CHANGE_CLOSING_TIME = "QUIZ_CREATION_CHANGE_CLOSING_TIME"
export const QUIZ_CREATION_CHANGE_MAX_ATTEMPTS = "QUIZ_CREATION_CHANGE_MAX_ATTEMPTS"
export const QUIZ_CREATION_TOGGLE_ATTEMPT_LIMIT = "QUIZ_CREATION_TOGGLE_ATTEMPT_LIMIT"
export const QUIZ_CREATION_TOGGLE_CONFIDENCE = "QUIZ_CREATION_TOGGLE_CONFIDENCE"

export const QUIZ_CREATION_UPDATE_QUESTIONS = "QUIZ_CREATION_UPDATE_QUESTIONS"

export const QUIZ_CREATION_CREATE_START = "QUIZ_CREATION_CREATE_START"
export const QUIZ_CREATION_CREATE_SUCCESS = "QUIZ_CREATION_CREATE_SUCCESS"
export const QUIZ_CREATION_CREATE_FAILURE = "QUIZ_CREATION_CREATE_FAILURE"
export const QUIZ_CREATION_RESET_NOTIFICATION = "QUIZ_CREATION_RESET_NOTIFICATION"
export const QUIZ_CREATION_RESET = "QUIZ_CREATION_RESET"
